use_frameworks!

target 'CVLoggerSwift_Example', :exclusive => true do
  pod 'CVLoggerSwift', :path => '../'
end

target 'CVLoggerSwift_Tests', :exclusive => true do
  pod 'CVLoggerSwift', :path => '../'

  pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end
