use_frameworks!

target 'CVLoggerSwift_Example', :exclusive => true do
  pod 'CVLoggerSwift', :path => '../'
end

target 'CVLoggerSwift_Tests', :exclusive => true do
  pod 'CVLoggerSwift', :path => '../'
end
